name: Build Apk

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release:
        description: 'Create a GitHub Release'
        required: true
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Sign key
      run: |
        echo "KEYSTORE_FILE=KeyStore.jks" >> ./gradle.properties
        echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> ./gradle.properties
        echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> ./gradle.properties
        echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> ./gradle.properties
        echo "${{ secrets.KEYSTORE }}" | base64 -d > ./app/KeyStore.jks
        sed -i "s/versionCode *[0-9]\+/versionCode ${{ github.run_number }}/" ./app/build.gradle

    - name: Set up JDK 17
      uses: actions/setup-java@v4.7.1
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build APK
      run: ./gradlew assembleRelease --stacktrace --warning-mode all

    - name: Get App Version Name
      run: |
        echo "APP_VERSION=$(grep versionName app/build.gradle | sed -n 's/.*versionName \"\([0-9.]*\)\".*/\1/p')" >> $GITHUB_ENV

    - name: Rename APK
      run: mv app/build/outputs/apk/release/*.apk Game-Unlocker-v${{ env.APP_VERSION }}-${{ github.run_number }}.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Game Unlocker
        path: Game-Unlocker-v${{ env.APP_VERSION }}-${{ github.run_number }}.apk
        retention-days: 7

    - name: Upload APK to Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_TOPIC_ID }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
      run: |
        python3 ./errorbot.py "Game-Unlocker-v${{ env.APP_VERSION }}-${{ github.run_number }}.apk"

    - name: Create Release
      if: ${{ github.event.inputs.release == 'true' }}
      id: create_release
      uses: softprops/action-gh-release@v2.3.2
      with:
        files: Game-Unlocker-v${{ env.APP_VERSION }}-${{ github.run_number }}.apk
        tag_name: ${{ env.APP_VERSION }}
        name: ${{ env.APP_VERSION }}
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
